#from the dockerdocs reference
name: Assignment04

#referencing the slides
services:
  frontend:
    #referencing dockerdocs/reference/compose-file
    #build looks within specified directory for a Dockerfile
    build: ./frontend
    #referenced from docker getting started todo webapp
    working_dir: /bookApp

  backend:
    build: ./backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: myAssignment04Password
      MYSQL_DB: test

  #mysql readme and docker's getting started to-do-webapp
  db:
    image: mysql
    environment:
      #according to mysql a password is mandatory
      MYSQL_ROOT_PASSWORD: myAssignment04Password
      MYSQL_DATABASE: test
