#from the dockerdocs reference
name: Assignment04

#referencing the slides
services:
  frontend:
    #referencing dockerdocs/reference/compose-file
    build: ./frontend

  backend:
    build: ./backend
