#from the dockerdocs reference
name: Assignment04

#referencing the slides
services:
  frontend:
    #referencing dockerdocs/reference/compose-file
    #build looks within specified directory for a Dockerfile
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #referenced from docker getting started todo webapp
    #mapping host5173 to container 5173
    ports:
      - 5173:5173
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #mapping local host8800 to container port 3000
    #to be able to send requests to our backend
    ports:
      - 8800:3000
    #gpt describes this as a weird strict way for backend to check credentials
    environment:
      MYSQL_HOST: db
      #backend is hardcoded to accept specific credentials
      MYSQL_USER: root
      MYSQL_PASSWORD: myAssignment04pswd
      MYSQL_DB: test
    depends_on:
      db:
        condition: service_healthy

  #mysql readme and docker's getting started to-do-webapp
  db:
    image: mysql:8.0
    #because apparently mysql as an immage has issues
    command: --default-authentication-plugin=mysql_native_password
    environment:
      #according to mysql a password is mandatory
      MYSQL_ROOT_PASSWORD: myAssignment04pswd
      MYSQL_DATABASE: test
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pmyAssignment04pswd"]
      interval: 5s
      timeout: 5s
      retries: 10
