#from the dockerdocs reference
name: Assignment04

#referencing the slides
services:
  frontend:
    #referencing dockerdocs/reference/compose-file
    #build looks within specified directory for a Dockerfile
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #referenced from docker getting started todo webapp
    #mapping host5173 to container 5173
    ports:
      - 8080:5173
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8081:3000

    #gpt describes this as a weird strict way for backend to check credentials
    environment:
      MYSQL_HOST: db
      MYSQL_USER: publisher
      MYSQL_PASSWORD: myAssignment04Password
      MYSQL_DB: test

  #mysql readme and docker's getting started to-do-webapp
  db:
    image: mysql
    environment:
      #according to mysql a password is mandatory
      MYSQL_ROOT_PASSWORD: myAssignment04Password
      MYSQL_DATABASE: test
