#from the dockerdocs reference
name: Assignment04

#referencing the slides
services:
  frontend:
    #referencing dockerdocs/reference/compose-file
    #build looks within specified directory for a Dockerfile
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #referenced from docker getting started todo webapp
    #mapping host5173 to container 5173
    ports:
      - 5173:5173
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #mapping local host8800 to container port 3000
    #to be able to send requests to our backend
    ports:
      - 8800:3000
    #gpt describes this as a weird strict way for backend to check credentials
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: myAssignment04Password
      MYSQL_DB: test
    depends_on:
      - localhost

  #mysql readme and docker's getting started to-do-webapp
  localhost:
    image: mysql
    environment:
      #according to mysql a password is mandatory
      MYSQL_ROOT_PASSWORD: myAssignment04Password
      MYSQL_DATABASE: test
